### ISSUE TITLE
I-JSON from Erik Nygren

### ISSUE THREAD

**Issue by evyncke** [IPv6-mPvD/mpvd-ietf-drafts#13]
For the PVD encoding topic, would it make sense to constrain to I-JSON [RFC7493 <https://tools.ietf.org/html/rfc7493>]? It looks like draft-sah-resolver-information-02 proposes going that way, and if that gets adopted in dnsop it seems likely that the same client software will likely be looking up PVDs and DNS resolver-information, and may want them to play well together. (eg, perhaps even with resolver-info being a child node of a PVD or referenced by a PVD?)

(possibly a duplicate of Erik's issue)

**Comment by tfpauly** [comment]
Added to #11
