### ISSUE TITLE
Suresh's comment on Section 3.1

### ISSUE THREAD

**Issue by evyncke** [IPv6-mPvD/mpvd-ietf-drafts#17]
> * Section 3.1
> 
> How is the Router Lifetime field processed if the R bit is set and the RA header is included? Is the intent that this will always supersede the “outer” Router Lifetime for PvD aware hosts? In any case this needs to be specified as it is not standard RFC4861 behavior.

**Comment by evyncke** [comment]
Section 3.4 answers Suresh's question and is quite explicit about it. Perhaps worth adding a x-ref to section 3.4 when describing the R-flag ?

**Comment by tfpauly** [comment]
Is it clear enough that the values in the PvD option supersede the other ones? Could we add a sentence just to make that extra clear? (Or am I missing that there already is one?)

**Comment by evyncke** [comment]
I think it is clear but if Suresh does not think so then we may add more text and esp add the reference to section 3.4

**Comment by tfpauly** [comment]
Addressed in df2eeb7
