### ISSUE TITLE
Suresh's comment on section 4.1

### ISSUE THREAD

**Issue by evyncke** [IPv6-mPvD/mpvd-ietf-drafts#19]
> * Section 4.1
> 
> "If the host has a temporary address per[RFC4941]
>    in this PvD, then hosts SHOULD use a temporary address to
>    fetch the PvD Additional Information and SHOULD deprecate the used
>    temporary address and generate a new temporary address afterward.”
> 
> Not sure why this behavior is required. Can you please explain?

**Comment by evyncke** [comment]
This is only for privacy, i.e., prevent the HTTPS server to track the host.

So, adding a sentence along this line should be OK. For example by prefixing the text with "In order to ensure privacy for the host, ..."

Also a typo in the text where host is used as singular and plural without any good reason.

**Comment by tfpauly** [comment]
Addressed in PR with d652db8
