### ISSUE TITLE
explicit PVDs SHOULD prefer different source addresses?

### ISSUE THREAD

**Issue by ekline** [IPv6-mPvD/mpvd-ietf-drafts#2]
-02 text currently says:

   In order to provide multiple different PvDs, a router MUST send
   multiple RAs.  Different explicit PvDs MAY be advertised with RAs
   using the same IPv6 source address; but different implicit PvDs,
   advertised by different RAs, MUST use different link-local addresses
   because these implicit PvDs are identified by the source addresses of
   the RAs.

I wonder if we can/should strengthen the text to clarify that even though explicit pvds MAY be signaled via the same src addr, they SHOULD be sent separately... Thoughts?

**Comment by Oryon** [comment]
So, after giving some more thoughts to this point, it is not really clear to me what the exact benefit is. I can see how, from an implementation perspective, it may help a router to differentiate traffic for different PvDs, but that can also be done by looking at the IP addresses used by the hosts, and I think the latter is the longer term best practice.
Can you clarify how this could help from the host perspective ?

**Comment by Oryon** [comment]
Hello,
Can I close this issue based on our hallway discussions ?

**Comment by Oryon** [comment]
Hello.
I'll close the issue for now. Feel free to re-open if necessary.
