### ISSUE TITLE
Suresh's comment on section 5

### ISSUE THREAD

**Issue by evyncke** [IPv6-mPvD/mpvd-ietf-drafts#20]
> * Section 5
> 
> I was thinking that there needs to be some host behavior to be specified related to the H bit and the sequence number here. If the H bit is set and the sequence number is unchanged from a previous successful query I think the host should refrain from sending another https query. If you agree, this needs to be written down.

**Comment by evyncke** [comment]
I still think that the expiration time ('expires' key) in the add. information should be followed.
The sequence number could be missed (it if rolled over and come back to its previous value -- host being disconnected for days or weeks) and it only for flash update. We could assume that some updates are not time critical and can be delayed until expiration.

Nevertheless, adding some text in the host behavior to specify the above paragraph is required indeed.

**Comment by tfpauly** [comment]
Added text with 511dd48.
