### ISSUE TITLE
Consider using applicaton/pvd+json

### ISSUE THREAD

**Issue by tfpauly** [IPv6-mPvD/mpvd-ietf-drafts#6]
Erik Kline wrote:

```
Would it be good to say that PvD HTTPS contents might be
served as applicaton/pvd+json OR application/pvd+cbor?  I quite like
Ole's CDDL specification style, and I also think we might want reserve
some space for "ietf" designated standard things.
```

**Comment by evyncke** [comment]
I also like the idea, but then ensure that the server MUST serve the two types of contents and that the client SHOULD use the `Accept` header to specify which one it can handled.
With perhaps a default?

**Comment by tfpauly** [comment]
I'm tempted to just leave the definition as JSON for now. But I will add the media type.

**Comment by tfpauly** [comment]
We do have `applicaton/pvd+json` now, closing issue for now.
