### ISSUE TITLE
Remove x-foo

### ISSUE THREAD

**Issue by tfpauly** [IPv6-mPvD/mpvd-ietf-drafts#7]
Erik Kline wrote:

```
Furthermore, I think that mentioning/recommending X-Foo is contrary to
https://tools.ietf.org/html/rfc6648 and we probably don't want to do
that.
```

**Comment by evyncke** [comment]
Indeed, let's rather use the 2-level key with this I-D using "ietf" as the first key, then our 3 values.

Of course, need to add some text for people wanting to add their own

**Comment by evyncke** [comment]
Tommy's text 

> New assignments for Additional Information PvD Keys Registry will be administered by IANA through Expert Review

 fixes this issue for me.
