### ISSUE TITLE
Checksum in inner RA

### ISSUE THREAD

**Issue by evyncke** [IPv6-mPvD/mpvd-ietf-drafts#9]
From Erik Kline email date 28th of March 2019 on 6MAN

> Instead of zero-ing out the type+code+checksum of the inner RA message
> header if present, why not just leave most of it alone?
> 
> If I might suggest:
> 
>     Type MUST be 134
>     Code MUST be 0
>     Checksum MUST be 0; non-zero checksums MUST be ignored by the receiver.
>

**Comment by tfpauly** [comment]
This is covered in #8
